name: Syntax Request
description: Requesting new syntax-highlight that does't exist in the repository
title: "[Request] "
labels: ["new"]
# assignees:
  # - guobao2333
body:
  - type: markdown
    attributes:
      value: |
        **Title example:** `[Request] Add JavaScript mtsx`
  - type: input
    id: name
    attributes:
      label: Language Official Name
      description: Official/Common/Conventional name of the language
      placeholder: e.g. `JavaScript`
    validations:
      required: true
  - type: textarea
    id: alias
    attributes:
      label: Alias (case insensitive)
      description: Another name for the language (optional)
      placeholder: e.g. `JS`
    validations:
      required: false
  - type: textarea
    id: suffix
    attributes:
      label: Suffix
      description: File extension using this language
      placeholder: e.g. `.js` `.cjs` `.mjs`
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Related Info
      description: Official grammar introduction and other information for the language
      # value: ""
      placeholder: |
        If you really cant find it, please use a wiki link instead, but filling it out correctly will help the maintainer complete it faster.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Supplementary Info
      description: If you find that this language has been highlighted elsewhere, you can attach relevant links and screenshots of the effects.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/guobao2333/MT-syntax-highlight?tab=readme-ov-file#request-new-language--%E8%AF%B7%E6%B1%82%E6%96%B0%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
